added pytest success awareness

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -27,18 +27,27 @@ jobs:
           # If you have a requirements file, uncomment the next line:
           pip install -r requirements.txt
 
-      #- name: Run pytest
+      - name: Run pytest
 
         # Using pytest is recommended for better reporting
-       # run: pytest
+        run: pytest
 
       - name: mattermost message
+        if: success() || failure() # Forces step to run even if pytest fails
         run: |
           if [ "${{ github.ref_name }}" = "main" ]; then
             TEAM_NAME="Collegium"
           else
             TEAM_NAME="Testing"
           fi
+          
+          
+          if [ "${{ job.status }}" = "success" ]; then
+            TEST_PASSED="True"
+          else
+            TEST_PASSED="False"
+          fi
+          
           
           SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
           COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
@@ -54,4 +63,5 @@ jobs:
             "$COMMIT_URL" \
             "$COMMIT_MSG" \
             "${{ github.repository }}" \
-            "${{ github.server_url }}"
+            "${{ github.server_url }}" \
+            "False"
